### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by JungYunHan** [JungYunHan/pre-project-react-tutorial#1]
### 만들고자 하는 기능이 무엇인가요?
Todo list 만들기

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] Todo list 보여주기 (Read)
2. [ ] Todo 추가하기 (Create)
3. [ ] Todo 수정하기 (Update)
4. [ ] Todo 삭제하기 (Delete)

### 예상 작업 시간
ex) 3h
